# Generated by Django 3.0.5 on 2020-04-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemtrack_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_template',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
