# Generated by Django 3.0.5 on 2020-04-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemtrack_app', '0002_category_template_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_template',
            name='order',
        ),
        migrations.RemoveField(
            model_name='descriptor_template',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='descriptor_template',
            name='order',
        ),
        migrations.AddField(
            model_name='record_category',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
