# Generated by Django 3.0.5 on 2020-08-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemtrack_app', '0003_auto_20200414_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record_category',
            name='order',
        ),
        migrations.RemoveField(
            model_name='record_descriptor',
            name='order',
        ),
        migrations.RemoveField(
            model_name='record_descriptor',
            name='record_id',
        ),
        migrations.AddField(
            model_name='record',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='record',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='category_template',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='category_template',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='descriptor_template',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='descriptor_template',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='record_descriptor',
            name='draft_statement',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='record_descriptor',
            name='feedback_statement',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='record_descriptor',
            name='final_statement',
            field=models.TextField(default=''),
        ),
    ]
