# Generated by Django 3.0.5 on 2020-09-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemtrack_app', '0006_auto_20200928_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record_category',
            old_name='level',
            new_name='draft_level',
        ),
        migrations.AddField(
            model_name='record_category',
            name='feedback_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record_category',
            name='final_level',
            field=models.IntegerField(default=0),
        ),
    ]
