# Generated by Django 3.0.5 on 2020-09-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemtrack_app', '0007_auto_20200929_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record_descriptor',
            name='draft_statement',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record_descriptor',
            name='feedback_statement',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='record_descriptor',
            name='final_statement',
            field=models.TextField(blank=True, default=''),
        ),
    ]
