# Generated by Django 3.0.5 on 2020-10-01 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chemtrack_app', '0008_auto_20200929_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='student_cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_as_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='teacher_cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_as_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
