# Generated by Django 3.0.5 on 2020-10-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemtrack_app', '0009_auto_20201001_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='student_cid',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='teacher_cid',
            new_name='teacher',
        ),
    ]
