# Generated by Django 3.0.5 on 2020-10-01 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chemtrack_app', '0010_auto_20201001_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='student_cid',
        ),
        migrations.AddField(
            model_name='record',
            name='student',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
