# Generated by Django 3.0.5 on 2020-10-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemtrack_app', '0012_auto_20201001_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='levels',
            field=models.IntegerField(default=0),
        ),
    ]
